---
development:
  cloud_name: dpxxczsnk
  api_key: '272224698591391'
  api_secret: vwRwXux9dzhnnf7qrhcUJkc8LeA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dpxxczsnk
  api_key: '272224698591391'
  api_secret: vwRwXux9dzhnnf7qrhcUJkc8LeA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dpxxczsnk
  api_key: '272224698591391'
  api_secret: vwRwXux9dzhnnf7qrhcUJkc8LeA
  enhance_image_tag: true
  static_image_support: false
